apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
data:
  vault-config.json: |
    {
      "backend": {
        "consul": {
          "address": "consul:8500",
          "path": "vault/"
        }
      },
      "listener": {
        "tcp":{
          "address": "0.0.0.0:8200",
          "tls_disable": 1
        }
      },
      "ui": true
    }
