apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi  # Adjust the storage size as needed to container 
 