# templates/vault-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
spec:
  replicas: {{ .Values.vault.replicas }}
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault
        image: {{ .Values.vault.image }}
        ports:
        - containerPort: 8200
        volumeMounts:
        - name: vault-config
          mountPath: /vault/config
        - name: vault-policies
          mountPath: /vault/policies
        - name: vault-data
          mountPath: /vault/data
        - name: vault-logs
          mountPath: /vault/logs
      volumes:
      - name: vault-config
        configMap:
          name: vault-config
      - name: vault-policies
        configMap:
          name: vault-policies
      - name: vault-data
        persistentVolumeClaim:
          claimName: vault-data-pvc
      - name: vault-logs
        persistentVolumeClaim:
          claimName: vault-logs-pvc
